project_name: "taskcluster-notify"
secrets:
  aws_access_key_id: ".Values.awsAccessKeyId"
  aws_region: ".Values.awsRegion"
  azure_account: ".Values.tfAzureAccount"
  denylisted_notification_table_name: "DenylistedNotification"
  email_blacklist: "[]"
  email_source_address: ".Values.emailSourceAddress"
  force_ssl: "false"
  irc_nick: ".Values.ircNick"
  irc_password: ".Values.ircPassword"
  irc_port: ".Values.ircPort"
  irc_real_name: ".Values.ircRealName"
  irc_user_name: ".Values.ircUserName"
  monitoring_enable: "true"
  node_env: "production"
  publish_metadata: "false"
  pulse_hostname: ".Values.pulseHostname"
  pulse_password: ".Values.pulsePassword"
  pulse_username: ".Values.pulseUsername"
  pulse_vhost: ".Values.pulseVhost"
  sqs_queue: ".Values.sqsQueue"
  taskcluster_access_token: ".Values.notifyAccessToken"
  taskcluster_client_id: "static/taskcluster/notify"
  trust_proxy: "true"
deployments:
  - service_name: "notify"
    docker_image: ".Values.dockerImage"
    proc_name: "web"
    readiness_path: "/api/notify/v1/ping"
    root_url: ".Values.rootUrl"
  - service_name: "notify"
    background_job: true
    docker_image: ".Values.dockerImage"
    proc_name: "handler"
    root_url: ".Values.rootUrl"
  - service_name: "notify"
    background_job: true
    docker_image: ".Values.dockerImage"
    proc_name: "irc"
    root_url: ".Values.rootUrl"
    secret_name: "taskcluster-notify"
