project_name: "taskcluster-web-server"
secrets:
  taskcluster_client_id: "static/taskcluster/web-server"
  taskcluster_access_token: ".Values.webServerAccessToken"
  node_env: "production"
  monitoring_enable: "true"
  monitoring_project: "taskcluster-web-server"
  pulse_username: ".Values.pulseUsername"
  pulse_password: ".Values.pulsePassword"
  pulse_hostname: ".Values.pulseHostname"
  pulse_vhost: ".Values.pulseVhost"
  login_strategies: ""
  public_url: ".Values.rootUrl"
deployments:
  - service_name: "web-server"
    proc_name: "web"
    secret_name: "taskcluster-web-server"
    root_url: ".Values.rootUrl"
    docker_image: ".Values.dockerImage"
    readiness_path: "/.well-known/apollo/server-health"
